server {
    listen       443 ssl;
    server_name  ${OTTERWIKI_DOMAIN};

    ssl_certificate     /etc/letsencrypt/live/${OTTERWIKI_DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${OTTERWIKI_DOMAIN}/privkey.pem;
    client_max_body_size 0;

    location / {
        try_files $uri @app;
    }

    location @app {
        uwsgi_pass web:9090;
        include /etc/nginx/uwsgi_params;
        uwsgi_param Host $host;
        uwsgi_param X-Real-IP $remote_addr;
        uwsgi_param X-Forwarded-For $proxy_add_x_forwarded_for;
        uwsgi_param X-Forwarded-Proto $http_x_forwarded_proto;
    }

    location /static {
        alias /app/otterwiki/static;
    }

    location = /openvpn/wiki/DataChannelOffload {
        return 301 $scheme://$host/DataChannelOffload;
    }

    # Specific redirects for pages that are not under "Pages" layout
    location ~ ^/openvpn/wiki/(?<dco_page>DataChannelOffload/.*) {
        return 301 $scheme://$host/$dco_page;
    }

    # Generic redirect that handles many pages. Tested and works, even with multi-level pages.
    location ~ ^/openvpn/wiki/(?<page>.*) {
        return 301 $scheme://$host/Pages/$page;
    }

    location /openvpn {
        root /usr/share/nginx/openvpn;
        try_files $uri $uri/ $uri.html =404;

        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        location /openvpn/ticket {
            default_type "text/html";
        }
     }
}
